---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kty-server
  labels:
    app.kubernetes.io/component: server
rules:
  - apiGroups: ['']
    resources:
      - users
      - groups
    verbs:
      - impersonate
  - apiGroups:
      - kty.dev
    resources:
      - keys
      - keys/status
    verbs: ['*']
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - patch
    resourceNames:
      - keys.kty.dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kty-server
  labels:
    app.kubernetes.io/component: server
subjects:
  - kind: ServiceAccount
    name: kty-server
roleRef:
  kind: ClusterRole
  name: kty-server
  apiGroup: rbac.authorization.k8s.io
