---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kty-server
  labels:
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  ports:
    - port: 2222
  selector:
    app.kubernetes.io/component: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'

    spec:
      serviceAccountName: kty-server

      containers:
        - name: server
          image: gcr.io/grampelberg/kty:latest

          command: ['kty']
          args:
            - serve
            - -vv
            - --address=0.0.0.0
            - --key=/etc/kty/key/id_ed25519

          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
