allowed-duplicate-crates = [
    "base64",
    "bitflags",
    "crossterm",
    "h2",
    "heck",
    "http",
    "http-body",
    "hyper",
    "hyper-tls",
    "mio",
    "pbkdf2",
    "regex-automata",
    "regex-syntax",
    "reqwest",
    "rustls-pemfile",
    "syn",
    "sync_wrapper",
    "system-configuration",
    "system-configuration-sys",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "winreg",
]
