[tools]
"cargo:cargo-audit" = "0.20.0"
"cargo:cargo-binstall" = "1.7.4"
"cargo:cargo-outdated" = "0.15.0"
"npm:prettier" = "3.3.2"
"npm:prettier-plugin-toml" = "2.0.1"
just = "1.34.0"
helm = "3.15.4"
"cargo:git-cliff" = "2.5.0"
