[package]
name = "kuberift"
version.workspace = true
authors.workspace = true
description = "SSH into a Kubernetes cluster"
documentation.workspace = true
license-file.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[workspace.package]
version = "0.1.0"
authors = ["Thomas Rampelberg <thomas@saunter.org>"]
documentation = "https://docs.rs/kubrift"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/grampelberg/kuberift"
keywords = ["cli"]
categories = ["command-line-interface"]

[dependencies]
async-trait = "0.1.81"
backon = "0.4.4"
base64 = "0.22.1"
cata = { version = "0.1.1", path = "../cata" }
clap = { version = "4.5.9", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.0"
color-eyre = "0.6.3"
eyre = "0.6.12"
indicatif = { version = "0.17.8", features = ["tokio", "futures"] }
itertools = "0.13.0"
jsonwebtoken = "9.3.0"
open = "5.3.0"
reqwest = { version = "0.12.5", features = ["json", "stream", "multipart"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_path_to_error = "0.1.16"
tokio = { version = "1.38.1", features = ["full"] }
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[lints]
workspace = true

[profile.dev]
debug = 0
split-debuginfo = "unpacked"

[workspace.lints.rust]
missing_docs = "warn"
keyword-idents = "warn"
let-underscore = "warn"
rust-2024-compatibility = "warn"
unused_crate_dependencies = "warn"

[workspace.lints.clippy]
multiple_crate_versions = "warn"
cargo = "warn"
complexity = "warn"
correctness = "warn"
pedantic = "warn"
perf = "warn"
style = "warn"
suspicious = "warn"
missing_errors_doc = "allow"
