{{- with .Values -}}
{{ if has "gateway" .tags }}

{{- if .envoy.enabled -}}
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kty
  labels:
    {{- include "labels" (dict "name" "kty" "component" "gateway" "global" $) | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kty
  labels:
     {{- include "labels" (dict "name" "kty" "component" "gateway" "global" $) | nindent 4 }}
spec:
  gatewayClassName: kty
  listeners:
  - name: ssh
    protocol: TCP
    port: 2222
    allowedRoutes:
      kinds:
      - kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: kty
  labels:
    {{- include "labels" (dict "name" "kty" "component" "gateway" "global" $) | nindent 4 }}
spec:
  parentRefs:
  - name: kty
    sectionName: ssh
  rules:
  - backendRefs:
    - name: server
      port: 2222
{{- end }}
{{- end }}
