{{- with .Values.server -}}
{{- if (default .rbac true) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberift-server
  labels:
    {{- include "labels" (dict "name" "kuberift-server" "component" "server" "global" $) | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberift-server
  labels:
    {{- include "labels" (dict "name" "kuberift-server" "component" "server" "global" $) | nindent 4 }}
rules:
  - apiGroups: ['']
    resources:
      - users
      - groups
    verbs:
      - impersonate
  - apiGroups:
      - kuberift.com
    resources:
      - keys
      - keys/status
    verbs: ['*']
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - patch
    resourceNames:
      - keys.kuberift.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberift-server
  labels:
    {{- include "labels" (dict "name" "kuberift-server" "component" "server" "global" $) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kuberift-server
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kuberift-server
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
