apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kty-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kty-server
    app.kubernetes.io/part-of: kty
    app.kubernetes.io/managed-by: kty-cli
subjects:
  - kind: ServiceAccount
    name: kty-server
    namespace: kty
roleRef:
  kind: ClusterRole
  name: kty-server
  apiGroup: rbac.authorization.k8s.io
