apiVersion: v1
kind: Secret
metadata:
  name: kty-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: kty
    app.kubernetes.io/managed-by: kty-cli
data:
  placeholder: ''
