apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kty-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kty-server
    app.kubernetes.io/part-of: kty
    app.kubernetes.io/managed-by: kty-cli
rules:
  - apiGroups: ['']
    resources:
      - users
      - groups
    verbs:
      - impersonate
  - apiGroups:
      - kty.dev
    resources:
      - keys
      - keys/status
    verbs: ['*']
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - patch
    resourceNames:
      - keys.kty.dev
