apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: kty
    app.kubernetes.io/managed-by: kty-cli
spec:
  type: LoadBalancer
  ports:
    - port: 2222
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: kty
    app.kubernetes.io/managed-by: kty-cli
