apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: server
      app.kubernetes.io/part-of: kty
      app.kubernetes.io/managed-by: kty-cli
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: server
        app.kubernetes.io/part-of: kty
        app.kubernetes.io/managed-by: kty-cli
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'

    spec:
      serviceAccountName: kty-server

      containers:
        - name: server
          image: gcr.io/grampelberg/kty:latest

          # If you're not using this through `kty resources`, you'll need to
          # either remove the --key argument or provide a PKCS#8 private key in
          # the secret.
          command: ['kty']
          args:
            - serve
            - -vv
            - --address=0.0.0.0
            - --key=/etc/kty/key/id_ed25519

          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080

          volumeMounts:
            - mountPath: /etc/kty/key
              name: host-key
              readOnly: true

      volumes:
        - name: host-key
          secret:
            secretName: kty-server
