name: build

on:
  pull_request:
    branches:
      - main

  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  IMAGE: ghcr.io/grampelberg/kuberift

concurrency:
  group: |-
    build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  binary:
    runs-on: ${{ matrix.host_os }}

    strategy:
      matrix:
        os: [darwin]
        arch:
          - arm64

        include:
          - arch: arm64
            host_os: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install toolchain
        run: |-
          rustup show active-toolchain

      - uses: Swatinem/rust-cache@v2

      # There appears to be an issue with getting 403s from github when trying to use binstall on macs. Manually install any required tools for the build.
      # - uses: cargo-bins/cargo-binstall@main
      # - uses: jdx/mise-action@v2
      #   with:
      #     experimental: true
      - uses: taiki-e/install-action@v2
        with:
          tool: just,git-cliff,ripgrep

      - name: build
        run: just replace-version build-binary

      - name: rename
        run: |-
          cp target/release/kuberift kuberift-${{ matrix.os }}-${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: kuberift-${{ matrix.os }}-${{ matrix.arch }}
          path: kuberift*
          retention-days: 1

  docker:
    runs-on: ${{ matrix.host_os }}

    permissions:
      packages: write

    strategy:
      matrix:
        os: [linux]
        arch:
          - amd64
          # The emulated arm64 builds are painfully slow (90m last time). Skip them until we have dedicated linux-arm64 hardware.
          # - arm64

        include:
          - arch: amd64
            host_os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@v2
        with:
          tool: just,git-cliff,ripgrep
      - name: set version
        run: just replace-version

      - name: meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=ref,event=tag
            type=raw,value=unstable,enable={{is_default_branch}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: buildx
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/kuberift.dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: ${{ github.event_name != 'pull_request' }}
          outputs: |-
            type=image,name=${{ env.IMAGE }},push-by-digest=true,name-canonical=true

      - name: create digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.os }}-${{ matrix.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
