name: check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just lint

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just fmt-check

  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just audit
