name: check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

concurrency:
  group: |-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just lint

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: |-
          rustup show active-toolchain
          rustup install --profile default nightly

      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just fmt-check

  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just audit
