name: check-signed-commits
on:
  pull_request_target:
    branches:
      - main

jobs:
  check-signed-commits:
    name: verify-signed-commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
